shamefullyHoist: true

packages:
  - playground

catalog:
  "@antfu/eslint-config": ^4.16.2
  "@types/node": ^24.0.10
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.0
  chokidar: ^4.0.3
  consola: ^3.4.2
  cross-env: ^7.0.3
  empathic: ^2.0.0
  eslint: ^9.30.1
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.14
  tsdown: ^0.12.9
  tsx: ^4.20.3

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
