packages:
  - packages/*
  - playground
onlyBuiltDependencies:
  - esbuild
catalog:
  "@antfu/eslint-config": ^4.11.0
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.13.14
  "@zinkawaii/eslint-config": ^0.2.1
  bumpp: ^10.1.0
  chokidar: ^4.0.3
  consola: ^3.4.2
  crypto-es: ^2.1.0
  eslint: ^9.23.0
  find-cache-dir: ^5.0.0
  fs-extra: ^11.3.0
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.12
  tsup: ^8.4.0
  tsx: ^4.19.3
  vitest: ^3.0.9