shamefullyHoist: true

packages:
  - playground

catalog:
  "@types/node": ^24.3.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.3
  chokidar: ^4.0.3
  consola: ^3.4.2
  cross-env: ^10.0.0
  empathic: ^2.0.0
  eslint: ^9.33.0
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.14
  tsdown: ^0.14.1

onlyBuiltDependencies:
  - rolldown
  - unrs-resolver
