shamefullyHoist: true

packages:
  - playground

catalog:
  "@types/node": ^25.0.3
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.2
  chokidar: ^5.0.0
  consola: ^3.4.2
  cross-env: ^10.1.0
  empathic: ^2.0.0
  eslint: ^9.39.2
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.15
  tsdown: ^0.18.4
