shamefullyHoist: true

packages:
  - playground

catalog:
  "@antfu/eslint-config": ^4.13.2
  "@types/node": ^22.15.29
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  chokidar: ^4.0.3
  consola: ^3.4.2
  cross-env: ^7.0.3
  empathic: ^1.1.0
  eslint: ^9.28.0
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.14
  tsdown: ^0.12.5
  tsx: ^4.19.4

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
