packages:
  - playground

catalog:
  "@antfu/eslint-config": ^4.13.0
  "@types/node": ^22.15.17
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.0
  chokidar: ^4.0.3
  consola: ^3.4.2
  cross-env: ^7.0.3
  empathic: ^1.1.0
  eslint: ^9.26.0
  gray-matter: ^4.0.3
  pathe: ^2.0.3
  tinyglobby: ^0.2.13
  tsdown: ^0.11.5
  tsx: ^4.19.4

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
